### ISSUE TITLE
Memories 화면 개발

### ISSUE THREAD

**Issue by huhsay** [boostcampth/boostcamp3_H#100]
## 요구사항
1. 로컬 DB에 저장되어 있는 recall(추억)목록을 불러와 보여준다.

2. 'recall(추억)'은 다음과 같은 값이 필요하다.
 - 추억의 시작 날과 끝날
 - 랜덤으로 선택한 감정
 - 선택된 감정과 일치하는 일기리스트(추억이 생성되는 날로부터 2주동안의 일기목록이다)

3. 일기데이터는 다음과 같은 값을 가져야한다.
 - 선택된 감정
 - 일기가 작성된 날짜
 - 녹음 파일이 저장된 경로

### 1. data class 설계
* Memories 요구사항 2에 고려하여 설계한다.

### 2. repository 인터페이스 설계
요구 사항 1을 만족할 수 있는 인터페이스를 설계 합니다.
우리는 RxJava의 stream을 return해주기로 했던 걸 기억하세요.

### 3. repository 인터페이스 구현
PR 2에서 작성한 인터페이스를 구현합니다. room관련된 클래스 들은 이 단계에서 만듭시다.

### 4. presenter 구현 및 view 인터페이스 설계
PR 2에서 정의한 인터페이스만을 알아야 함에 주의 합시다.

### 5. view 구현
PR 4에서 정의한 view인터페이스를 구현합니다.

**Comment by zeropol2** [comment]
요구사항은 보통 개발 시작 전에 쓰는 것이기 때문에 개발을 모르는 사람이 썼다고 생각하고 작성을 해주시는 게 좋습니다.
구현을 쓰는게 아니고 실제로 무슨 일을 하는 건지 이해할수 있게 작성해주세요.
유저가 요구사항만 봤을 때 아 이게 무슨 기능이구나 생각할 수 있게끔 작성해주세요. 기획 문서라고 생각하시면 됩니다.

**Comment by zeropol2** [comment]
여전히 요구사항이 불분명합니다.

1. 로컬DB에 저장되어 있는 메모리즈 목록을 불러와서 보여준다.
2. 메모리즈는 일주일간 저장된 일기 중에서 특정한 기분의 일기모음이며, 여기서 특정한 기분은 랜덤으로 선택 된다.
3. 하나의 메모리즈는 다음과 같은 정보를 노출한다.
    - 기분
    - 생성 날짜
    - 해당 기분에 해당하는 일기 목록


이렇게 하는게 좀 더 이해하기가 쉽지 않을까요?

기획자의 마음으로 요구사항을 정의하세요.

**Comment by zeropol2** [comment]
이름은 메모리즈 말고 다른 이름 없을까요? 단수형으로요~

**Comment by zeropol2** [comment]
그리고 화면 디자인 한거 보시면 일기목록도 보여져야 하는데 거기에 대한 내용이 빠진 것 같아요~

**Comment by zeropol2** [comment]
정확히는 추억이 생성된 날짜가 아니고 추억의 시점이지 않을까요(적당한 단어가 떠오르지 않네요) 
왜냐하면 1월 2째주에 1월 첫째주의 추억을 생성하면 추억이 생성된 날짜는 1월2째주지만, 우리가 필요한 값은 1월 2째주가 아닌 1월 첫째주니깐요. 현재 워딩은 혼돈을 주는 것 같습니다.

**Comment by zeropol2** [comment]
* 생성된 날짜와 랜덤으로 선택된 감을을 바탕으로한 제목 <- 요건 위에서 언급하신 날짜와 감정으로 조합할수 있는 값이므로 별도로 언급이 필요 없을것 같네요

**Comment by zeropol2** [comment]
일기 재생에 대한 설명이 빠진 것 같네요.
