### ISSUE TITLE
통계 화면 개발

### ISSUE THREAD

**Issue by WooVictory** [boostcampth/boostcamp3_H#102]
## 요구사항
1. 로컬 DB에 저장되어 있는 데이터 중 사용자가 선택한 감정과 분석한 감정에 대한 수치와 해시태그를 가져온다.
   * 가져온 감정 데이터는 이번주를 기준으로 요일에 따라서 내가 선택한 감정과 분석한 감정을 꺾은선 그래프를 통해 보여준다.
   * 사용자가 한주 동안 녹음할 때 저장한 해시태그를 가져와서 어떠한 태그를 달았는지 등장한 횟수에 따라 색상을 변경하여 보여준다. 이로 인해 한 주 동안 어땠는지 파악할 수 있다.
2. 통계를 위해 들어있어야 하는 정보는 다음과 같다.
   * 사용자가 선택한 감정에 대한 수치
   * 분석한 감정에 대한 수치
   * 날짜

### 1. data class 설계
- 그래프를 그릴 수 있는 데이터를 가져와서 받을 수 있는 data class를 설계합니다.
- 해시태그를 그릴 수 있는 데이터를 가져와서 받을 수 있는 data class를 설계합니다.

### 2. repository 인터페이스 설계
요구 사항 1을 만족할 수 있는 인터페이스를 설계 합니다.
우리는 RxJava의 stream을 return해주기로 했던 걸 기억하세요.

### 3. repository 인터페이스 구현
PR 2에서 작성한 인터페이스를 구현합니다. room관련된 클래스 들은 이 단계에서 만듭시다.

### 4. presenter 구현 및 view 인터페이스 설계
PR 2에서 정의한 인터페이스만을 알아야 함에 주의 합시다. 

### 5. view 구현
PR 4에서 정의한 view인터페이스를 구현합니다.

**Comment by zeropol2** [comment]
요구사항이 좀 더 구체적으로 정의되면 좋겠네요~
이승우님 말고 다른 분이 보고도 개발할 수 있게요~

제가 이해한 바로는 해당 화면에서는 
1. 그래프
2. 태그 목록
크게 이렇게 두개의 뷰를 보여준다는 것인가요?


해당 그래프에는 무슨 데이터를 보여주는건지
태그 목록은 어떤 걸 보여준다는 건지 설명이 좀 더 필요할 것 같아요
